// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZYGJOvtHPXygcHmR6YQpHKxJEEvMAHs0',
    appId: '1:1088141472431:web:e64e2565d48976654fda5a',
    messagingSenderId: '1088141472431',
    projectId: 'invfnl',
    authDomain: 'invfnl.firebaseapp.com',
    databaseURL: 'https://invfnl-default-rtdb.firebaseio.com',
    storageBucket: 'invfnl.firebasestorage.app',
    measurementId: 'G-LQC8KHVTZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB7fZ-yX7iah6aTI7mVtV_u8Wjchr34Hk',
    appId: '1:1088141472431:android:3d512bcf538dfcce4fda5a',
    messagingSenderId: '1088141472431',
    projectId: 'invfnl',
    databaseURL: 'https://invfnl-default-rtdb.firebaseio.com',
    storageBucket: 'invfnl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqm9FaHSUejo9Gw1kBlqXjYN3J5ogTtMw',
    appId: '1:1088141472431:ios:742efb2ab4173b324fda5a',
    messagingSenderId: '1088141472431',
    projectId: 'invfnl',
    databaseURL: 'https://invfnl-default-rtdb.firebaseio.com',
    storageBucket: 'invfnl.firebasestorage.app',
    iosBundleId: 'com.example.sistemaRiegoInvernadero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqm9FaHSUejo9Gw1kBlqXjYN3J5ogTtMw',
    appId: '1:1088141472431:ios:742efb2ab4173b324fda5a',
    messagingSenderId: '1088141472431',
    projectId: 'invfnl',
    databaseURL: 'https://invfnl-default-rtdb.firebaseio.com',
    storageBucket: 'invfnl.firebasestorage.app',
    iosBundleId: 'com.example.sistemaRiegoInvernadero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZYGJOvtHPXygcHmR6YQpHKxJEEvMAHs0',
    appId: '1:1088141472431:web:a84144d2b9ff22a24fda5a',
    messagingSenderId: '1088141472431',
    projectId: 'invfnl',
    authDomain: 'invfnl.firebaseapp.com',
    databaseURL: 'https://invfnl-default-rtdb.firebaseio.com',
    storageBucket: 'invfnl.firebasestorage.app',
    measurementId: 'G-6QT15QNGGH',
  );
}
